version: "3.6"
services:
  mysql:
    image: mysql:5.7.22
    container_name: "mysql-tdcsp2019"
    environment:
      MYSQL_DATABASE: devtest
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - tdcsp2019
networks:
  tdcsp2019:
