CREATE TABLE T_PRODUCT (
    ID SERIAL PRIMARY KEY,
	TXT_NAME VARCHAR (50) UNIQUE NOT NULL,
	TXT_DESCRIPTION VARCHAR (50) NOT NULL
);

INSERT INTO T_PRODUCT(TXT_NAME, TXT_DESCRIPTION) VALUES ('product1', 'description product 1');