# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Project 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 11
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B package \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=claudenirfreitas \
          -Dsonar.projectKey=quarkus-microservice-test \
          -Dsonar.java.coveragePlugin=cobertura \           
          sonar:sonar
        cp target/quarkus-microservice-test-1.0.0-SNAPSHOT-runner.jar docker/app.jar

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:        
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: claudenirfreitas/quarkus-microservice-test/quarkus-test
        tag_with_ref: true 
